version: "3.6"

services:
  centos7:
    image: centos:7
    container_name: centos7
    command: tail -f /dev/null
  ubuntu:
    image: pycontribs/ubuntu:latest
    container_name: ubuntu
    command: tail -f /dev/null
    